import type { Metadata } from "next";
import 'easymde/dist/easymde.min.css'

export const metadata: Metadata = {
  title: "nextjs project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
